.RECIPEPREFIX +=


vgg:
    wget "https://onedrive.live.com/download?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21361854&authkey=APMgqT4vLOkSEtY" -O "coco_val_vgg_fc7.pth";
    wget "https://onedrive.live.com/embed?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21361856&authkey=ACxmPUfJB15L02k" -O "coco_train_vgg_fc7.pth";

resnet:
    wget "https://onedrive.live.com/download?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21361855&authkey=AHdY1TwG0xwem1A" -O "coco_train_resnet152_pool5.pth";
    wget "https://onedrive.live.com/download?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21361855&authkey=AHdY1TwG0xwem1A" -O "coco_val_resnet152_pool5.pth";
    