.RECIPEPREFIX +=


vgg16:
    wget --no-check-certificate "https://onedrive.live.com/download?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21364924&authkey=AJzdq7TLwxSIoe4" -O "coco_train_vgg16_fc7.pth";
    wget --no-check-certificate "https://onedrive.live.com/download?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21364925&authkey=AAefrzCFKniSxwY" -O "coco_val_vgg16_fc7.pth";

vgg19_bn:
    wget --no-check-certificate "https://onedrive.live.com/download?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21364923&authkey=ABOahsDHSYdBR6E" -O "coco_train_vgg19_bn_fc7.pth";
    wget --no-check-certificate "https://onedrive.live.com/download?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21364922&authkey=ADOPHUsMBGGBxM4" -O "coco_val_vgg19_bn_fc7.pth";

resnet152:
    wget --no-check-certificate "https://onedrive.live.com/download?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21364927&authkey=ALJ_ccvtjFFn8FU" -O "coco_train_resnet152_pool5.pth";
    wget --no-check-certificate "https://onedrive.live.com/download?cid=8D14A7BAB8A67CED&resid=8D14A7BAB8A67CED%21364926&authkey=AOaX7pBm2E-gxnM" -O "coco_val_resnet152_pool5.pth";